"""Mail provider abstraction. Mock returns deterministic demo data;
real implementation talks to Gmail API.
"""
from __future__ import annotations

import asyncio
import base64
import logging
import random
import threading
import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from email.utils import parseaddr
from typing import Any

from app.config import settings

log = logging.getLogger(__name__)

_GMAIL_READONLY_SCOPE = "https://www.googleapis.com/auth/gmail.readonly"
_MAX_GOOGLE_ATTEMPTS = 4
_RETRYABLE_HTTP_STATUS_CODES = {429, 500, 502, 503, 504}


class GmailProviderError(RuntimeError):
    """Base error for failures while calling Gmail."""


class GmailAuthError(GmailProviderError):
    """OAuth credentials must be regenerated by the user."""


@dataclass
class IncomingAttachment:
    filename: str
    content: bytes
    mime_type: str = "application/octet-stream"
    attachment_id: str | None = None


@dataclass
class IncomingMessage:
    external_id: str
    sender: str
    subject: str
    body: str
    received_at: str  # ISO
    attachments: list[IncomingAttachment] = field(default_factory=list)


class MailProvider(ABC):
    @abstractmethod
    async def fetch_message(self, message_id: str) -> IncomingMessage: ...

    @abstractmethod
    async def list_recent(self, max_results: int = 20) -> list[IncomingMessage]: ...

    @abstractmethod
    async def download_attachment(self, message_id: str, attachment_id: str) -> bytes: ...


# ----- mock ---------------------------------------------------------------

_DEMO = [
    {
        "sender": "biuro@abctransport.pl",
        "subject": "Dokumenty sierpien",
        "body": "Przesylam wyciag bankowy i leasing za sierpien 2026.",
        "files": [
            ("wyciag.pdf", b"[Mock PDF] Wyciag bankowy ABC Transport 2026-08"),
            ("leasing.pdf", b"[Mock PDF] Umowa leasingu ABC Transport"),
        ],
    },
    {
        "sender": "kontakt@janex.com.pl",
        "subject": "Faktury sierpien",
        "body": "W zalaczeniu faktury sprzedazy za sierpien.",
        "files": [
            ("faktury.zip", b"[Mock ZIP] Faktury sprzedazy Janex 2026-08"),
        ],
    },
    {
        "sender": "biuro@kowalski.pl",
        "subject": "Raport kasowy - sierpien",
        "body": "Przesylam raport kasowy za sierpien.",
        "files": [
            ("raport_kasowy.pdf", b"[Mock PDF] Raport kasowy Kowalski 2026-08"),
        ],
    },
]


class MockMailProvider(MailProvider):
    """Returns a deterministic, in-memory inbox for local demo / tests."""

    async def fetch_message(self, message_id: str) -> IncomingMessage:
        for i, m in enumerate(_DEMO):
            if message_id == f"mock-{i}":
                return _to_message(i, m)
        raise KeyError(message_id)

    async def list_recent(self, max_results: int = 20) -> list[IncomingMessage]:
        return [_to_message(i, m) for i, m in enumerate(_DEMO[:max_results])]

    async def download_attachment(self, message_id: str, attachment_id: str) -> bytes:
        raise KeyError(f"mock attachment not found: {message_id}/{attachment_id}")


def _to_message(idx: int, raw: dict) -> IncomingMessage:
    return IncomingMessage(
        external_id=f"mock-{idx}",
        sender=raw["sender"],
        subject=raw["subject"],
        body=raw["body"],
        received_at="2026-08-31T09:00:00+00:00",
        attachments=[
            IncomingAttachment(filename=name, content=data, mime_type="application/pdf")
            for name, data in raw["files"]
        ],
    )


# ----- gmail --------------------------------------------------------------


def _retry_delay(attempt: int, error: Exception) -> float:
    """Return a bounded delay, honoring Google's Retry-After when present."""
    response = getattr(error, "resp", None)
    retry_after = (
        response.get("Retry-After") or response.get("retry-after")
        if response is not None
        else None
    )
    try:
        seconds = float(retry_after)
    except (TypeError, ValueError):
        seconds = (2 ** (attempt - 1)) + random.uniform(0, 0.25)
    return min(max(seconds, 0.25), 30.0)


def _refresh_error_message(error: Exception) -> str:
    text = str(error).lower()
    if "invalid_grant" in text:
        return (
            "Google odrzucił refresh token (invalid_grant). Token mógł zostać "
            "odwołany albo pochodzić z innego klienta OAuth; wygeneruj nowy token."
        )
    if "revoked" in text or "expired" in text:
        return (
            "Token OAuth został odwołany lub wygasł. Nadaj ponownie dostęp do "
            "Gmaila i zapisz nowy refresh token."
        )
    return "Google odrzucił token OAuth. Sprawdź konfigurację klienta OAuth i nadane zakresy."


class GmailProvider(MailProvider):
    """Real Gmail API implementation. Auth: OAuth2 with refresh token.

    Google access tokens are short-lived and are refreshed automatically by
    ``google-auth``. A single lock also prevents concurrent background tasks
    from refreshing the same credentials at the same time, which is a common
    source of intermittent failures when several attachments are downloaded.
    """

    def __init__(self, client_id: str, client_secret: str, refresh_token: str) -> None:
        from google.oauth2.credentials import Credentials

        self._creds = Credentials(
            token=None,
            refresh_token=refresh_token,
            client_id=client_id,
            client_secret=client_secret,
            token_uri="https://oauth2.googleapis.com/token",
            scopes=[_GMAIL_READONLY_SCOPE],
        )
        self._service = None
        self._request_lock = threading.RLock()

    def _svc(self):
        if self._service is None:
            from googleapiclient.discovery import build

            # Discovery is inexpensive to lazy-load and avoids doing network
            # work while the application is importing its configuration.
            with self._request_lock:
                if self._service is None:
                    self._service = build(
                        "gmail",
                        "v1",
                        credentials=self._creds,
                        cache_discovery=False,
                    )
        return self._service

    def _execute(self, request: Any) -> Any:
        """Execute a read-only Google request with bounded retry/backoff."""
        from google.auth.exceptions import RefreshError
        from googleapiclient.errors import HttpError
        from httplib2 import HttpLib2Error

        last_error: Exception | None = None
        for attempt in range(1, _MAX_GOOGLE_ATTEMPTS + 1):
            try:
                # The lock covers execute(), including the automatic OAuth
                # refresh performed by google-auth before the HTTP request.
                with self._request_lock:
                    return request.execute()
            except RefreshError as exc:
                raise GmailAuthError(_refresh_error_message(exc)) from exc
            except HttpError as exc:
                status = getattr(exc.resp, "status", None)
                try:
                    status = int(status)
                except (TypeError, ValueError):
                    status = None
                if status == 401:
                    raise GmailAuthError(
                        "Google odrzucił token (HTTP 401). Sprawdź, czy refresh token "
                        "ma zakres gmail.readonly i nie został odwołany."
                    ) from exc
                if status in _RETRYABLE_HTTP_STATUS_CODES:
                    last_error = exc
                    if attempt == _MAX_GOOGLE_ATTEMPTS:
                        break
                    delay = _retry_delay(attempt, exc)
                    log.warning(
                        "Google API returned HTTP %s; retrying in %.2fs (attempt %s/%s)",
                        status,
                        delay,
                        attempt,
                        _MAX_GOOGLE_ATTEMPTS,
                    )
                    time.sleep(delay)
                    continue
                raise GmailProviderError(f"Google API request failed with HTTP {status}.") from exc
            except (ConnectionError, TimeoutError, OSError, HttpLib2Error) as exc:
                last_error = exc
                if attempt == _MAX_GOOGLE_ATTEMPTS:
                    break
                delay = _retry_delay(attempt, exc)
                log.warning(
                    "Google API request failed with %s; retrying in %.2fs (attempt %s/%s)",
                    type(exc).__name__,
                    delay,
                    attempt,
                    _MAX_GOOGLE_ATTEMPTS,
                )
                time.sleep(delay)

        raise GmailProviderError(
            f"Google API request failed after {_MAX_GOOGLE_ATTEMPTS} attempts: "
            f"{type(last_error).__name__}"
        ) from last_error

    async def fetch_message(self, message_id: str) -> IncomingMessage:
        def _do() -> IncomingMessage:
            svc = self._svc()
            request = svc.users().messages().get(
                userId="me", id=message_id, format="full"
            )
            msg = self._execute(request)
            return _parse_gmail(msg)

        return await asyncio.to_thread(_do)

    async def download_attachment(self, message_id: str, attachment_id: str) -> bytes:
        def _do() -> bytes:
            svc = self._svc()
            request = (
                svc.users()
                .messages()
                .attachments()
                .get(
                    userId="me",
                    messageId=message_id,
                    id=attachment_id,
                )
            )
            attachment = self._execute(request)
            data = attachment.get("data", "")
            if not data:
                return b""
            data += "=" * (-len(data) % 4)
            return base64.urlsafe_b64decode(data)

        return await asyncio.to_thread(_do)

    async def list_recent(self, max_results: int = 20) -> list[IncomingMessage]:
        def _do() -> list[IncomingMessage]:
            svc = self._svc()
            listing = self._execute(
                svc.users()
                .messages()
                .list(
                    userId="me",
                    maxResults=max_results,
                    q="has:attachment newer_than:7d",
                )
            )
            out: list[IncomingMessage] = []
            for ref in listing.get("messages", []):
                request = svc.users().messages().get(
                    userId="me", id=ref["id"], format="full"
                )
                out.append(_parse_gmail(self._execute(request)))
            return out

        return await asyncio.to_thread(_do)


def _parse_gmail(msg: dict) -> IncomingMessage:
    """Parse Gmail message into IncomingMessage."""
    headers = {
        h["name"].lower(): h["value"]
        for h in msg.get("payload", {}).get("headers", [])
    }

    raw_from = headers.get("from", "")
    _, sender = parseaddr(raw_from)

    subject = headers.get("subject", "")
    external_id = msg.get("id", "") or str(uuid.uuid4())

    body = ""
    attachments: list[IncomingAttachment] = []

    def walk(part: dict):
        nonlocal body

        mime = part.get("mimeType", "")
        filename = part.get("filename") or ""
        part_body = part.get("body", {})

        # Treść maila
        if mime == "text/plain" and "data" in part_body:
            body += base64.urlsafe_b64decode(
                part_body["data"] + "=="
            ).decode("utf-8", errors="ignore")

        # Załącznik
        if filename and "attachmentId" in part_body:
            attachments.append(
                IncomingAttachment(
                    filename=filename,
                    content=b"",
                    mime_type=mime,
                    attachment_id=part_body["attachmentId"],
                )
            )

        for child in part.get("parts", []) or []:
            walk(child)

    walk(msg.get("payload", {}))

    return IncomingMessage(
        external_id=external_id,
        sender=sender.lower(),
        subject=subject,
        body=body,
        received_at=headers.get("date", ""),
        attachments=attachments,
    )


# ----- factory ------------------------------------------------------------

_provider: MailProvider | None = None


def get_mail_provider() -> MailProvider:
    global _provider
    if _provider is not None:
        return _provider

    if settings.mail_provider == "gmail":
        missing = [
            name
            for name, value in (
                ("GOOGLE_CLIENT_ID", settings.google_client_id),
                ("GOOGLE_CLIENT_SECRET", settings.google_client_secret),
                ("GOOGLE_REFRESH_TOKEN", settings.google_refresh_token),
            )
            if not str(value or "").strip()
        ]
        if missing:
            raise GmailProviderError(
                "MAIL_PROVIDER=gmail wymaga ustawienia: " + ", ".join(missing)
            )
        _provider = GmailProvider(
            settings.google_client_id.strip(),
            settings.google_client_secret.strip(),
            settings.google_refresh_token.strip(),
        )
    else:
        _provider = MockMailProvider()
    return _provider
